services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - monitor-net

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/monitor
    networks:
      - monitor-net
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - monitor-net
    depends_on:
      - backend

volumes:
  mongo_data:

networks:
  monitor-net:
