FROM node:slim

# Crear directorio de trabajo
WORKDIR /app

# Copiar archivos de configuración
COPY package*.json ./

# Instalar dependencias (incluye devDependencies)
RUN npm install

# Copiar el resto de los archivos
COPY . .

# Instalar nodemon de forma global (opcional si ya está en devDependencies)
# RUN npm install -g nodemon

# Exponer el puerto
EXPOSE 4000

# Comando para desarrollo
CMD ["npm", "run", "dev"]
